@startuml
class FileMetadataNotFoundByIdException {
    + FileMetadataNotFoundByIdException()
    + FileMetadataNotFoundByIdException(message:string?)
}
Exception <|-- FileMetadataNotFoundByIdException
@enduml
