version: "3.7"
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y
    networks:
      - app-tier
  db:
    container_name: "storage-mariadb"
    hostname: "db"
    image: mariadb/server:10.5
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: "Qwerty123"
        MARIADB_DATABASE: "root"
        MARIADB_USER: "user"
        MARIADB_PASSWORD: "Qwerty123"
    ports: 
      - '3608:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks: 
      - app-tier 
  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data/s3
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_REGION: "us-east-1"
    command: server --console-address :9001 /data/s3
    networks: 
      - app-tier
networks:
  app-tier:
    driver: bridge
    
volumes: 
  mariadb-data:
  minio-data: