@startuml
!include .\\.\src\Profile.Storage\Program.puml
!include .\\.\src\Profile.Storage\Startup.puml
!include .\\.\src\Profile.Storage.Application\DeletionCronService.puml
!include .\\.\src\Profile.Storage.Application\ServiceRegistry.puml
!include .\\.\src\Profile.Storage.Migrations\Program.puml
!include .\\.\src\Profile.Storage.Persistence\FileLocalProvider.puml
!include .\\.\src\Profile.Storage.Persistence\FileMemoryProvider.puml
!include .\\.\src\Profile.Storage.Persistence\FileMetadataRepository.puml
!include .\\.\src\Profile.Storage.Persistence\FileProviderFactory.puml
!include .\\.\src\Profile.Storage.Persistence\FileS3Provider.puml
!include .\\.\src\Profile.Storage.UnitTesting\FileProviderFactoryTests.puml
!include .\\.\src\Profile.Stripe.Api\StripeController.puml
!include .\\.\src\Profile.Storage.Api\Files\FileManagementController.puml
!include .\\.\src\Profile.Storage.Domain\Exceptions\FileMetadataNotFoundByIdException.puml
!include .\\.\src\Profile.Storage.Domain\Exceptions\FileNotFoundByNameException.puml
!include .\\.\src\Profile.Storage.Domain\Storage\ExistenceStatus.puml
!include .\\.\src\Profile.Storage.Domain\Storage\FileMetadata.puml
!include .\\.\src\Profile.Storage.Domain\Storage\FileStorageService.puml
!include .\\.\src\Profile.Storage.Domain\Storage\IFileMetadataRepository.puml
!include .\\.\src\Profile.Storage.Domain\Storage\IFileProvider.puml
!include .\\.\src\Profile.Storage.Domain\Storage\IFileProviderFactory.puml
!include .\\.\src\Profile.Storage.Domain\Storage\IFileStorageService.puml
!include .\\.\src\Profile.Storage.Domain\Storage\StorageType.puml
!include .\\.\src\Profile.Storage.Migrations\Config\FluentConfig.puml
!include .\\.\src\Profile.Storage.Migrations\Config\FluentDbContext.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\101_CreateMetadataTable.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\106_AddMetadataDateLoaded.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\111_AddMetadataFileExistanceColumn.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\116_ChangeTypeOfFileStatusColumnToBinary.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\121_ChangeTypeOfFileStatusToByte.puml
!include .\\.\src\Profile.Storage.Migrations\Migrations\126_AlterFileStatusAsByte.puml
!include .\\.\src\Profile.Storage.Persistence\Configs\BackgroundDeletionConfig.puml
!include .\\.\src\Profile.Storage.Persistence\Configs\DbConfig.puml
!include .\\.\src\Profile.Storage.Persistence\Configs\S3Config.puml
!include .\\.\src\Profile.Storage.Persistence\Configs\StorageConfig.puml
!include .\\.\src\Profile.Storage.Persistence\Configs\SwaggerGenConfig.puml
!include .\\.\src\Profile.Storage.Persistence\Context\FileStorageContext.puml
!include .\\.\src\Profile.Storage.Persistence\Mapping\FileStorageMetadataMapping.puml
!include .\\.\src\Profile.Storage.Persistence\Tools\EfMappingExtensions.puml
!include .\\.\src\Profile.Storage.Persistence\Tools\IEntityMappingConfiguration.puml
!include .\\.\src\Profile.Storage.UnitTesting\MockFileProvider\MockFileLocalProvider.puml
!include .\\.\src\Profile.Storage.UnitTesting\MockFileProvider\MockFileMemoryProvider.puml
!include .\\.\src\Profile.Storage.UnitTesting\MockFileProvider\MockFileS3Provider.puml
!include .\\.\src\Profile.Storage.UnitTesting\MockFileProvider\MockProviderFactory.puml
!include .\\.\src\Profile.Storage.Api\Files\Models\FileRequest.puml
!include .\\.\src\Profile.Storage.Api\Files\Models\FileResponse.puml
!include .\\.\src\Profile.Storage\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage\obj\Debug\net5.0\Profile.Storage.AssemblyInfo.puml
!include .\\.\src\Profile.Storage\obj\Debug\net5.0\Profile.Storage.MvcApplicationPartsAssemblyInfo.puml
!include .\\.\src\Profile.Storage\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage\obj\Release\net5.0\Profile.Storage.AssemblyInfo.puml
!include .\\.\src\Profile.Storage\obj\Release\net5.0\Profile.Storage.MvcApplicationPartsAssemblyInfo.puml
!include .\\.\src\Profile.Storage.Api\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Api\obj\Debug\net5.0\Profile.Storage.Api.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Api\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Api\obj\Release\net5.0\Profile.Storage.Api.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Application\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Application\obj\Debug\net5.0\Profile.Storage.Application.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Application\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Application\obj\Release\net5.0\Profile.Storage.Application.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Domain\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Domain\obj\Debug\net5.0\Profile.Storage.Domain.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Domain\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Domain\obj\Release\net5.0\Profile.Storage.Domain.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Migrations\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Migrations\obj\Debug\net5.0\Profile.Storage.Migrations.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Migrations\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Migrations\obj\Release\net5.0\Profile.Storage.Migrations.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Persistence\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Persistence\obj\Debug\net5.0\Profile.Storage.Persistence.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.Persistence\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.Persistence\obj\Release\net5.0\Profile.Storage.Persistence.AssemblyInfo.puml
!include .\\.\src\Profile.Storage.UnitTesting\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Storage.UnitTesting\obj\Debug\net5.0\Profile.Storage.UnitTesting.AssemblyInfo.puml
!include .\\.\src\Profile.Stripe.Api\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Stripe.Api\obj\Debug\net5.0\Profile.Storage.Api2.AssemblyInfo.puml
!include .\\.\src\Profile.Stripe.Api\obj\Debug\net5.0\Profile.Stripe.Api.AssemblyInfo.puml
!include .\\.\src\Profile.Stripe.Api\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\.\src\Profile.Stripe.Api\obj\Release\net5.0\Profile.Storage.Api2.AssemblyInfo.puml
@enduml
